cache_dir = "/var/lib/sccache-dist/cache"
public_addr = "__SERVER_PUBLIC_ADDR__"
bind_address = "0.0.0.0:10501"
scheduler_url = "__SCHEDULER_URL__"
[builder]
type = "docker"
[scheduler_auth]
type = "token"
token = "__TOKEN__"
